# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import logging

from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.main import FastRAMQPI

from mo_sor import events
from mo_sor.autogenerated_graphql_client import GraphQLClient
from mo_sor.config import _Settings

GRAPHQL_VERSION = 30


def _listeners() -> list[Listener]:
    return [
        Listener(
            namespace="mo",
            user_key="org_unit",
            routing_key="org_unit",
            path="/org_unit",
            parallelism=1,
        ),
    ]


def create_app() -> FastAPI:
    settings = _Settings()

    fastramqpi = FastRAMQPI(
        application_name="mo-sor",
        settings=settings.fastramqpi,
        graphql_version=GRAPHQL_VERSION,
        graphql_client_cls=GraphQLClient,
        graphql_events=GraphQLEvents(
            declare_listeners=_listeners(),
        ),
    )
    fastramqpi.add_context(settings=settings)

    app = fastramqpi.get_app()
    app.include_router(events.router)

    logging.getLogger("httpx").setLevel(logging.WARNING)

    return app
