# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import logging

from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.events import Namespace
from fastramqpi.main import FastRAMQPI

from mo_sor import events
from mo_sor import ingest
from mo_sor.autogenerated_graphql_client import GraphQLClient
from mo_sor.config import _Settings
from mo_sor.database import Base
from mo_sor.dumps import Dumps

GRAPHQL_VERSION = 30


def _listeners() -> list[Listener]:
    return [
        Listener(
            namespace="mo",
            user_key="org_unit",
            routing_key="org_unit",
            path="/org_unit",
            parallelism=1,
        ),
    ]


def create_app() -> FastAPI:
    settings = _Settings()

    fastramqpi = FastRAMQPI(
        application_name="mo-sor",
        settings=settings.fastramqpi,
        graphql_version=GRAPHQL_VERSION,
        graphql_client_cls=GraphQLClient,
        graphql_events=GraphQLEvents(
            declare_namespaces=[Namespace(name=ingest.NAMESPACE)],
            declare_listeners=_listeners(),
        ),
        database_metadata=Base.metadata,
    )
    fastramqpi.add_context(settings=settings)
    fastramqpi.add_context(
        dumps=Dumps(
            settings.sor_file_pattern, settings.sor_root_code, settings.sor_root_name
        )
    )

    app = fastramqpi.get_app()
    app.include_router(events.router)
    app.include_router(ingest.router)

    logging.getLogger("httpx").setLevel(logging.WARNING)

    return app
