# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""SOR dumps in MO's file store.

The supplier uploads the dumps to the EXPORTS file store, with the dump date in
the file name.
"""

from datetime import date
from datetime import datetime

from async_lru import alru_cache
from pydantic import BaseModel

from mo_sor.autogenerated_graphql_client import FileStore
from mo_sor.autogenerated_graphql_client import GraphQLClient
from mo_sor.sor_file import SorUnit
from mo_sor.sor_file import parse


class DumpNotFound(Exception):
    pass


class Dump(BaseModel, frozen=True):
    file_name: str
    date: date
    units: dict[str, SorUnit]


def dump_date(file_name: str, pattern: str) -> date | None:
    """Return the dump date from a file name, or None if it is not a dump."""
    try:
        # Only the date is used, so the missing timezone does not matter
        return datetime.strptime(file_name, pattern).date()  # noqa: DTZ007
    except ValueError:
        return None


class Dumps:
    """Lists, reads and parses the dumps in the file store."""

    def __init__(self, pattern: str, root_code: str, root_name: str) -> None:
        self.pattern = pattern
        self.root_code = root_code
        self.root_name = root_name

    async def list(self, mo: GraphQLClient) -> list[tuple[date, str]]:
        """List the dumps in the file store, oldest first."""
        files = await mo.list_files(FileStore.EXPORTS)
        dumps = []
        for file in files.objects:
            file_date = dump_date(file.file_name, self.pattern)
            if file_date is not None:
                dumps.append((file_date, file.file_name))
        return sorted(dumps)

    # Every event reads the newest dump, so cache it rather than download and
    # parse it once per event. Ingesting a dump also reads the previous one to
    # diff against, hence two. Errors are not cached, so a broken dump that the
    # supplier uploads again under the same name is read again.
    @alru_cache(maxsize=2)
    async def load(self, mo: GraphQLClient, file_name: str) -> Dump:
        """Load and parse a dump.

        Raises:
            DumpNotFound: If there is no dump with this name.
            InvalidSorFile: If the dump fails validation.
        """
        file_date = dump_date(file_name, self.pattern)
        if file_date is None:
            raise DumpNotFound(f"{file_name} does not match {self.pattern}")
        files = await mo.read_file(FileStore.EXPORTS, file_name)
        if not files.objects:
            raise DumpNotFound(f"{file_name} is not in the file store")
        units = parse(files.objects[0].text_contents, self.root_code, self.root_name)
        return Dump(file_name=file_name, date=file_date, units=units)
