# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Ingest: turn the newest SOR dump into sor/unit events."""

import asyncio

import structlog
from fastapi import APIRouter
from fastramqpi.depends import Sessionmaker
from pydantic import BaseModel
from sqlalchemy import select

from mo_sor import depends
from mo_sor.autogenerated_graphql_client import EventSendInput
from mo_sor.autogenerated_graphql_client import GraphQLClient
from mo_sor.database import LastApplied
from mo_sor.diff import diff
from mo_sor.sor_file import InvalidSorFile

NAMESPACE = "sor"
ROUTING_KEY = "unit"

router = APIRouter()
logger = structlog.stdlib.get_logger()


class Ingested(BaseModel):
    file_name: str
    added: list[str]
    changed: list[str]
    removed: list[str]


async def send_events(mo: GraphQLClient, codes: set[str]) -> None:
    async with asyncio.TaskGroup() as tg:
        for code in sorted(codes):
            tg.create_task(
                mo.send_event(
                    input=EventSendInput(
                        namespace=NAMESPACE, routing_key=ROUTING_KEY, subject=code
                    )
                )
            )


@router.post("/ingest")
async def ingest(
    settings: depends.Settings,
    mo: depends.GraphQLClient,
    dumps: depends.Dumps,
    sessionmaker: Sessionmaker,
    dry_run: bool = False,
    force: bool = False,
) -> Ingested | None:
    """Send a sor/unit event for each unit that changed since the last ingest.

    Only the newest dump is compared to the last ingested one. Dumps in
    between are skipped, as the event handler always reads the newest dump.

    Does nothing if the newest dump is invalid, or removes more than
    `sor_max_terminations` units unless `force` is set. Both are logged as
    errors.

    With `dry_run`, returns what would be ingested without sending events or
    recording anything.
    """
    listing = await dumps.list(mo)
    if not listing:
        return None
    _, file_name = listing[-1]

    async with sessionmaker() as session:
        last = await session.scalar(select(LastApplied))
    if last is not None and last.file_name == file_name:
        return None

    try:
        dump = await dumps.load(mo, file_name)
    except InvalidSorFile as e:
        logger.error("Invalid SOR dump", file_name=file_name, errors=e.errors)
        return None
    # Without a last ingested dump, every unit in the newest dump is added
    previous = await dumps.load(mo, last.file_name) if last is not None else None

    d = diff(previous.units if previous else None, dump.units)
    if len(d.removed) > settings.sor_max_terminations and not force:
        logger.error(
            "Too many terminations in SOR dump",
            file_name=file_name,
            terminations=len(d.removed),
            max_terminations=settings.sor_max_terminations,
        )
        return None

    ingested = Ingested(
        file_name=file_name,
        added=sorted(d.added),
        changed=sorted(d.changed),
        removed=sorted(d.removed),
    )
    if dry_run:
        return ingested

    logger.info(
        "Ingesting SOR dump",
        file_name=file_name,
        added=len(d.added),
        changed=len(d.changed),
        removed=len(d.removed),
    )
    # Events are sent before the dump is recorded, so if we crash in between,
    # the next ingest sends them again rather than losing them. An event sent
    # twice is harmless, as the handler reads the newest dump either way.
    await send_events(mo, d.codes)
    async with sessionmaker() as session, session.begin():
        await session.merge(LastApplied(id=1, file_name=file_name))
    return ingested
