# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10
    hooks:
      - id: ruff
        args: [ --fix ]
        language: system
      - id: ruff-format
        language: system

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.4.0
    hooks:
      - id: mypy
        args: [ --config-file=pyproject.toml ]
        language: system

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.19.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ pre-push ]

  - repo: https://github.com/fpgmaas/deptry.git
    rev: 0.25.1
    hooks:
      - id: deptry
        language: system
