# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

query GetOrgUnit($uuid: UUID!) {
  org_units(filter: {uuids: [$uuid]}) {
    objects {
      current {
        uuid
        user_key
        name
      }
    }
  }
}

query ListFiles($file_store: FileStore!) {
  files(filter: {file_store: $file_store}) {
    objects {
      file_name
    }
  }
}

query ReadFile($file_store: FileStore!, $file_name: String!) {
  files(filter: {file_store: $file_store, file_names: [$file_name]}) {
    objects {
      text_contents
    }
  }
}

mutation SendEvent($input: EventSendInput!) {
  event_send(input: $input)
}

mutation DeclareEventListener($input: ListenerCreateInput!) {
  event_listener_declare(input: $input) {
    uuid
  }
}

query ListEvents($listener: UUID!) {
  events(filter: {listeners: {uuids: [$listener]}}) {
    objects {
      subject
    }
  }
}

query FetchEvent($listener: UUID!) {
  event_fetch(filter: {listener: $listener}) {
    token
    subject
  }
}

mutation AcknowledgeEvent($token: EventToken!) {
  event_acknowledge(input: {token: $token})
}
