# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import AsyncIterator
from collections.abc import Awaitable
from collections.abc import Callable

import pytest
from fastapi import FastAPI
from httpx import AsyncClient

from mo_sor.app import GRAPHQL_VERSION
from mo_sor.app import create_app
from mo_sor.autogenerated_graphql_client import GraphQLClient


@pytest.fixture
async def app() -> FastAPI:
    """Override the FastRAMQPI `app` fixture.

    The FastRAMQPI `test_client`/`server` fixtures run this app under a real
    uvicorn server, so the GraphQL event system delivers MO events to it.
    """
    return create_app()


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    """Authenticated GraphQL codegen client for OS2mo."""
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v{GRAPHQL_VERSION}",
        http_client=mo_client,
    )
    async with graphql_client as client:
        yield client


UploadFile = Callable[[str, str], Awaitable[None]]


@pytest.fixture
def upload_file(mo_client: AsyncClient) -> UploadFile:
    """Upload a file to MO's EXPORTS file store, overwriting any existing one.

    The codegen client cannot send the multipart request that `upload_file`
    requires, so this is done by hand.
    """

    async def upload(file_name: str, contents: str) -> None:
        operations = {
            "query": (
                "mutation($file: Upload!) "
                "{ upload_file(file_store: EXPORTS, file: $file, force: true) }"
            ),
            "variables": {"file": None},
        }
        # An empty filename makes these form fields rather than files
        form: dict[str, tuple[str, str | bytes]] = {
            "operations": ("", json.dumps(operations)),
            "map": ("", json.dumps({"file": ["variables.file"]})),
            "file": (file_name, contents.encode("utf-8")),
        }
        r = await mo_client.post(f"/graphql/v{GRAPHQL_VERSION}", files=form)
        r.raise_for_status()
        assert "errors" not in r.json(), r.json()

    return upload
