# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import date

import pytest

from mo_sor.autogenerated_graphql_client import GraphQLClient
from mo_sor.dumps import DumpNotFound
from mo_sor.dumps import Dumps
from mo_sor.sor_file import InvalidSorFile
from tests.integration.conftest import UploadFile
from tests.sor_dumps import dump
from tests.sor_dumps import row

PATTERN = "SOR_Region_%d%m%y.csv"
# Made-up codes in the shape of real ones, with valid check digits
ROOT = "1001000016005"
CHILD = "100001000016006"
VALID = dump(row(ROOT))
VALID_WITH_CHILD = dump(row(ROOT), row(CHILD, ROOT, level=2))
INVALID = "not a dump"

APRIL_30 = "SOR_Region_300426.csv"
MAY_1 = "SOR_Region_010526.csv"


@pytest.mark.integration_test
async def test_list_sorts_by_date_not_name(
    graphql_client: GraphQLClient, upload_file: UploadFile
) -> None:
    """DDMMYY does not sort as text."""
    await upload_file(MAY_1, VALID)
    await upload_file(APRIL_30, VALID)
    await upload_file("sor_report.csv", "")

    assert await Dumps(PATTERN, ROOT, "SOR").list(graphql_client) == [
        (date(2026, 4, 30), APRIL_30),
        (date(2026, 5, 1), MAY_1),
    ]


@pytest.mark.integration_test
async def test_load(graphql_client: GraphQLClient, upload_file: UploadFile) -> None:
    await upload_file(APRIL_30, VALID)

    dump = await Dumps(PATTERN, ROOT, "SOR").load(graphql_client, APRIL_30)

    assert dump.file_name == APRIL_30
    assert dump.date == date(2026, 4, 30)
    assert dump.units.keys() == {ROOT}


@pytest.mark.integration_test
async def test_load_missing_file(graphql_client: GraphQLClient) -> None:
    with pytest.raises(DumpNotFound):
        await Dumps(PATTERN, ROOT, "SOR").load(graphql_client, APRIL_30)


@pytest.mark.integration_test
async def test_load_name_not_matching_pattern(
    graphql_client: GraphQLClient, upload_file: UploadFile
) -> None:
    await upload_file("sor_report.csv", VALID)
    with pytest.raises(DumpNotFound):
        await Dumps(PATTERN, ROOT, "SOR").load(graphql_client, "sor_report.csv")


@pytest.mark.integration_test
async def test_load_invalid_file(
    graphql_client: GraphQLClient, upload_file: UploadFile
) -> None:
    await upload_file(APRIL_30, INVALID)
    with pytest.raises(InvalidSorFile):
        await Dumps(PATTERN, ROOT, "SOR").load(graphql_client, APRIL_30)


@pytest.mark.integration_test
async def test_load_is_cached(
    graphql_client: GraphQLClient, upload_file: UploadFile
) -> None:
    """Every event reads the newest dump; don't download it for each."""
    dumps = Dumps(PATTERN, ROOT, "SOR")
    await upload_file(APRIL_30, VALID)
    await dumps.load(graphql_client, APRIL_30)

    # Overwriting the file in MO is not seen while it is cached
    await upload_file(APRIL_30, VALID_WITH_CHILD)
    dump = await dumps.load(graphql_client, APRIL_30)
    assert dump.units.keys() == {ROOT}


@pytest.mark.integration_test
async def test_invalid_file_is_not_cached(
    graphql_client: GraphQLClient, upload_file: UploadFile
) -> None:
    """The supplier fixes a broken dump by uploading it again."""
    dumps = Dumps(PATTERN, ROOT, "SOR")
    await upload_file(APRIL_30, INVALID)
    with pytest.raises(InvalidSorFile):
        await dumps.load(graphql_client, APRIL_30)

    await upload_file(APRIL_30, VALID)
    dump = await dumps.load(graphql_client, APRIL_30)
    assert dump.units.keys() == {ROOT}
