# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import Awaitable
from collections.abc import Callable
from collections.abc import Iterable
from typing import Any

import pytest
from httpx import AsyncClient
from structlog.testing import capture_logs

from mo_sor.autogenerated_graphql_client import GraphQLClient
from mo_sor.autogenerated_graphql_client import ListenerCreateInput
from tests.integration.conftest import UploadFile
from tests.sor_dumps import dump
from tests.sor_dumps import row

# Made-up codes in the shape of real ones, with valid check digits. ROOT is
# SOR_ROOT_CODE in CI.
ROOT = "1001000016005"
A = "100001000016006"
B = "1000001000016004"
C = "20011000016005"

# SOR_FILE_PATTERN in CI is SOR_Region_%d%m%y.csv
MARCH_31 = "SOR_Region_310326.csv"
APRIL_30 = "SOR_Region_300426.csv"
MAY_1 = "SOR_Region_010526.csv"
MAY_2 = "SOR_Region_020526.csv"

ROOT_A_B = dump(row(ROOT), row(A, ROOT, level=2), row(B, ROOT, level=2))

DrainEvents = Callable[[], Awaitable[set[str]]]


@pytest.fixture
async def sor_events(
    test_client: AsyncClient, graphql_client: GraphQLClient
) -> DrainEvents:
    """Subjects of the sor/unit events sent since the last call."""
    # The app declares the "sor" namespace on startup (test_client)
    listener = await graphql_client.declare_event_listener(
        input=ListenerCreateInput(namespace="sor", routing_key="unit", user_key="test")
    )

    async def drain() -> set[str]:
        subjects = set()
        # `event_fetch` uses `for update skip locked` in MO, so it may return
        # null while events remain. `list_events` is a plain read, so we loop on
        # that instead.
        while (await graphql_client.list_events(listener.uuid)).objects:
            event = await graphql_client.fetch_event(listener.uuid)
            if event is not None:
                await graphql_client.acknowledge_event(event.token)
                subjects.add(event.subject)
        return subjects

    return drain


async def ingest(test_client: AsyncClient, **params: Any) -> dict[str, Any] | None:
    r = await test_client.post("/ingest", params=params)
    r.raise_for_status()
    return r.json()


def ingested(
    file_name: str,
    added: Iterable[str] = (),
    changed: Iterable[str] = (),
    removed: Iterable[str] = (),
) -> dict[str, Any]:
    return {
        "file_name": file_name,
        "added": sorted(added),
        "changed": sorted(changed),
        "removed": sorted(removed),
    }


@pytest.mark.integration_test
async def test_nothing_to_ingest(
    test_client: AsyncClient, sor_events: DrainEvents
) -> None:
    assert await ingest(test_client) is None
    assert await sor_events() == set()


@pytest.mark.integration_test
async def test_first_ingest_sends_every_unit_in_newest_dump(
    test_client: AsyncClient, upload_file: UploadFile, sor_events: DrainEvents
) -> None:
    """Without a previous ingest, everything in the newest dump is new.

    Older dumps are history and are not ingested.
    """
    await upload_file(APRIL_30, dump(row(ROOT)))
    await upload_file(MAY_1, ROOT_A_B)

    assert await ingest(test_client) == ingested(MAY_1, added={ROOT, A, B})
    assert await sor_events() == {ROOT, A, B}


@pytest.mark.integration_test
async def test_ingest_twice_does_nothing(
    test_client: AsyncClient, upload_file: UploadFile, sor_events: DrainEvents
) -> None:
    await upload_file(APRIL_30, ROOT_A_B)
    await ingest(test_client)
    await sor_events()

    assert await ingest(test_client) is None
    assert await sor_events() == set()


@pytest.mark.integration_test
async def test_dumps_in_between_are_skipped(
    test_client: AsyncClient, upload_file: UploadFile, sor_events: DrainEvents
) -> None:
    """Only the difference to the newest dump matters.

    B is renamed on May 1st and removed on May 2nd, so the rename is never
    sent on its own.
    """
    await upload_file(APRIL_30, ROOT_A_B)
    await ingest(test_client)
    await sor_events()

    await upload_file(
        MAY_1,
        dump(row(ROOT), row(A, ROOT, level=2), row(B, ROOT, name="Renamed", level=2)),
    )
    # May 2nd sorts before May 1st as text
    await upload_file(
        MAY_2, dump(row(ROOT), row(A, ROOT, level=2), row(C, ROOT, level=2))
    )

    assert await ingest(test_client) == ingested(MAY_2, added={C}, removed={B})
    assert await sor_events() == {B, C}


@pytest.mark.integration_test
async def test_dump_older_than_last_ingest_is_ignored(
    test_client: AsyncClient, upload_file: UploadFile, sor_events: DrainEvents
) -> None:
    await upload_file(APRIL_30, ROOT_A_B)
    await ingest(test_client)
    await sor_events()

    await upload_file(MARCH_31, dump(row(ROOT)))

    assert await ingest(test_client) is None
    assert await sor_events() == set()


@pytest.mark.integration_test
async def test_invalid_dump_is_not_ingested(
    test_client: AsyncClient, upload_file: UploadFile, sor_events: DrainEvents
) -> None:
    await upload_file(APRIL_30, ROOT_A_B)
    await ingest(test_client)
    await sor_events()

    await upload_file(MAY_1, "not a dump")

    with capture_logs() as cap_logs:
        assert await ingest(test_client) is None
    assert await sor_events() == set()
    errors = [log for log in cap_logs if log["log_level"] == "error"]
    assert [(log["event"], log["file_name"]) for log in errors] == [
        ("Invalid SOR dump", MAY_1)
    ]

    # The supplier uploads a fixed dump
    await upload_file(MAY_1, dump(row(ROOT), row(A, ROOT, level=2)))

    assert await ingest(test_client) == ingested(MAY_1, removed={B})
    assert await sor_events() == {B}


@pytest.mark.integration_test
@pytest.mark.envvar({"SOR_MAX_TERMINATIONS": "1"})
async def test_too_many_terminations_are_not_ingested(
    test_client: AsyncClient, upload_file: UploadFile, sor_events: DrainEvents
) -> None:
    await upload_file(APRIL_30, ROOT_A_B)
    await ingest(test_client)
    await sor_events()

    await upload_file(MAY_1, dump(row(ROOT)))

    with capture_logs() as cap_logs:
        assert await ingest(test_client) is None
    assert await sor_events() == set()
    errors = [log for log in cap_logs if log["log_level"] == "error"]
    assert [(log["event"], log["file_name"]) for log in errors] == [
        ("Too many terminations in SOR dump", MAY_1)
    ]

    # An operator checks the dump and forces it through
    assert await ingest(test_client, force=True) == ingested(MAY_1, removed={A, B})
    assert await sor_events() == {A, B}


@pytest.mark.integration_test
async def test_dry_run(
    test_client: AsyncClient, upload_file: UploadFile, sor_events: DrainEvents
) -> None:
    await upload_file(APRIL_30, ROOT_A_B)
    await ingest(test_client)
    await sor_events()

    await upload_file(MAY_1, dump(row(ROOT), row(A, ROOT, level=2)))
    expected = ingested(MAY_1, removed={B})

    assert await ingest(test_client, dry_run=True) == expected
    assert await sor_events() == set()

    # Nothing was recorded, so the real ingest does the same
    assert await ingest(test_client) == expected
    assert await sor_events() == {B}
